### ISSUE TITLE
Add a flag to go into the console on test case failure

### ISSUE THREAD

**Issue by fubuloubu** [iamdefinitelyahuman/brownie#443]
### Overview
Normally, when testing with `pytest` one can add the `--pdb` flag to have `pytest` enter into the debugger when a test failure occurs (allowing you to debug it). Brownie already has a console available, so having the test case enter into this mode (or even `pdb` more generally) on a failure to allow a debug would be helpful.

### Specification
Have a flag, like maybe `brownie test --debug`, that launches into an appropiate debug console to be able to introspect the conditions inside a test case, and be able to work with the contracts under test to identify what the failure might be. This mode might happen after all test cases have executed so that ordering doesn't become a problem, and it might want to revert the last transaction under certain scenarios.

**Comment by iamdefinitelyahuman** [comment]
I like it! I think implementation won't be trivial, but also not impossible.

1. After a test fails, rerun it and take a snapshot prior to every transaction.
2. When the test fails, revert the last transaction.
3. Output the test code with the lines that haven't run yet greyed out, and the trace for the pending fail.
4. Open the console with the namespace of the test. The user plays around and when finished, `exit()` and onto the next failed test.

Challenges I can see immediately are making it work with `xdist` and moving this functionality to the session teardown phase instead of happening as tests are failing. My gut tells me that the 2nd problem solves the 1st one.

Does what I'm describing make sense?

**Comment by iamdefinitelyahuman** [comment]
Did some experimenting, the basic functionality is possible with just 4 lines of code.

added to the `PytestBrownieRunner` class in  `brownie/test/managers/runner.py`:

```python
    def pytest_exception_interact(self, report):
        if report.failed:
            from brownie._cli.console import Console
            Console().interact()
```

It requires use of the `-s` flag, otherwise pytest's stdout capture breaks it. There'll be a fair bit of experimenting to get this right, but it's really encouraging to see how easy the core functionality can be added!

Related: [Pytest API documentation](https://docs.pytest.org/en/latest/reference.html#_pytest.hookspec.pytest_exception_interact)
