### ISSUE TITLE
Update `Contract.from_explorer` with new Etherscan API data

### ISSUE THREAD

**Issue by iamdefinitelyahuman** [iamdefinitelyahuman/brownie#489]
### Overview
The etherscan API recently added several fields to the `getsourcecode` endpoint:

* `EVMVersion` is the evm ruleset used when compiling
* `Proxy`: if `1` indicates that the contract is a proxy
* `Implementation`: the implementation address, when this contract is a proxy

By considering these fields, it should be possible to strengthen the logic in `Contract.from_explorer` to reduce the frequency of the `"Locally compiled and on-chain bytecode do not match!"` warning, and avoid needing the `as_proxy_for=` in many cases.

### Specification
* Nothing user facing should change.
* Take advantage of the extra data, if it is available.
* Do not assume the data is available - the blockscout API likely does not deliver it.

**Comment by patagonudo** [comment]
Hi, @iamdefinitelyahuman. Thank you very much for such a fantastic tool! I'm reaching out because the following contract throws the warning and I'd like to understand why. Thank you

`Contract.from_explorer("0xa6B71E26C5e0845f74c812102Ca7114b6a896AB2")`

https://api.etherscan.io/api?module=contract&action=getsourcecode&address=0xa6B71E26C5e0845f74c812102Ca7114b6a896AB2
